name = "moe-counter"
main = "dist/worker.js"
compatibility_date = "2024-02-27"
workers_dev = false

[[routes]]
pattern = "moe-counter.saihentai.qzz.io"
custom_domain = true

[build]
command = "npm run build"

[[d1_databases]]
binding = "DB"
database_name = "moe-counter"
database_id = "194c98d1-87bc-404f-b2b8-e7243c53076e"
